SS14.Launcher/Program.cs
SS14.Launcher/SS14.Launcher.csproj

it's a thing on russian locale at least, can't even launch the launcher in 4.7.2

fixes some windows machines unable to create secure TLS/SSL connection

---

PublishFiles/SS14.Launcher
PublishFiles/SS14.desktop
publish_linux.sh

More "double-click to run" on my system.

Add .desktop file to Linux distribution

---

SS14.Launcher/Models/Connector.cs

Not sure if this was ever null but for me it's always an empty string (Windows).

Fix direct connect

---

SS14.Launcher/Models/Connector.cs
SS14.Launcher/Models/Data/DataManager.cs
SS14.Launcher/Views/MainWindowTabs/OptionsTabView.xaml

##About the PR
Adds an option for dynamic PGO into the launcher under the name Experimental Performance Options.
Enabled by default.

Dynamic PGO option

---

SS14.Launcher/Utility/ZStd.cs

Port over zstd-nocrashpls fix

---

SS14.Launcher/Models/ServerStatus/ServerListCache.cs
SS14.Launcher/Program.cs
SS14.Launcher/ViewModels/MainWindowTabs/HomePageViewModel.cs
SS14.Launcher/ViewModels/MainWindowTabs/ServerEntryViewModel.cs
SS14.Launcher/ViewModels/MainWindowTabs/ServerListTabViewModel.cs
SS14.Launcher/Views/MainWindowTabs/HomePageView.xaml

I'm not that great with Avalonia's reactive UI stuff, so I fully expect this to need some code review before it'll be accepted.
If the user has <= 4 favorites, assumes that they might be interested in more servers, and therefore shows them suggestions from the main server list.
This is an attempt to implement the Rane proposal for the Everybody's Gone To The Lizard problem.

Server suggestions

---

SS14.Launcher/Models/Data/CVars.cs
SS14.Launcher/Program.cs

See https://github.com/space-wizards/SS14.Launcher/issues/80

Show Windows 7 warning every time PLEASE STOP ASKING US FOR HELP WITH IT JESUS CHRIST

---

SS14.Launcher/Program.cs
SS14.Launcher/Utility/Language.cs

Translation by @SaphireLattice

Add Windows 7 warning in Russian

---

.github/workflows/conflict-labeler.yml

Just copy-pasted from content repo

Add conflict labeler workflow

---

flake.lock
nix/package.nix
nix/wrapper.nix

- Include version in wrapped package name.
- Update flake lock to latest nixpkgs 23.05 version.

Update Nix package to 0.24.0

---

Launcher.props
SS14.Launcher/Api/AuthApi.cs
SS14.Launcher/Models/Connector.cs
SS14.Launcher/Utility/ZStd.cs
download_net_runtime.py
publish_linux.sh
publish_osx.sh
publish_windows.sh

Yeah it just works let's GOOOOOOOOOOOOOOOOOOOOOO

.NET 8 :soda:

---

SS14.Launcher/Utility/ServerTagInfer.cs

I've seen a few servers off the 18+ list with this.

Infer ERP as 18+ tag

---

SS14.Launcher/Views/MainWindowTabs/ServerEntryView.xaml
SS14.Launcher/Views/MainWindowTabs/ServerEntryView.xaml.cs
SS14.Launcher/Views/RowSideAlignedPanel.cs

https://github.com/space-wizards/SS14.Launcher/assets/39844191/a2026fa9-c6fc-4343-8ade-3f39947d1d51

Fancy server info link buttons

---

SS14.Launcher/Program.cs

Why version 1607? Cause i have no fucking clue what to set it to!
Windows build versions here
https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions

Change minimum windows version to windows 10 version 1607

---

SS14.Launcher/Helpers.cs
SS14.Launcher/Models/Data/CVars.cs
SS14.Launcher/Program.cs
SS14.Launcher/VcRedistCheck.cs

Resolves #24
People... do this? Welp one issue down

Wine check & Windows popup helper

---

SS14.Launcher/Models/Connector.cs
SS14.Launcher/Models/Data/CVars.cs
SS14.Launcher/ViewModels/MainWindowTabs/OptionsTabViewModel.cs
SS14.Launcher/Views/MainWindowTabs/OptionsTabView.xaml

As far as I know, no one has experienced an issue with it. May as well remove some clutter. And make sure its on by default

Remove dynamic PGO option and make it default

---

flake.lock
nix/package.nix

Also update flake.lock
Upstreamed here: https://github.com/NixOS/nixpkgs/pull/294854

Update nix package to 0.26.0

---

default.nix
flake.lock
flake.nix
nix/package.nix

also added flake-compat for those who refuse to use flakes
not upstreaming this to nixpkgs anymore until further notice
tested:

Update nix package to 0.27.2

---

.github/workflows/publish-release.yml

MUDA MUDA MUDA MUDA (Well at least pjb said its useless now SOOOO)

Remove setup dotnet from the publish

---

SS14.Launcher/Assets/Locale/en-US/text.ftl
SS14.Launcher/Assets/Locale/ru/text.ftl
SS14.Launcher/ViewModels/Login/LoginViewModel.cs
SS14.Launcher/Views/Login/LoginView.xaml

Added checkbox "Show Password" to show or hide password characters.

Add Show Password checkbox

---

SS14.Launcher/ViewModels/MainWindowLoginViewModel.cs
SS14.Launcher/ViewModels/MainWindowViewModel.cs
SS14.Launcher/Views/MainWindowContent.xaml
SS14.Launcher/Views/MainWindowLogin.xaml
SS14.Launcher/Views/MainWindowTabs/OptionsTabView.xaml

Now comes with coding warcrimes (in my opinion)
(and tiny ass minor code style fix)

Show launcher version in the main window

---

.github/workflows/build-test.yml
Launcher.props
SS14.Launcher/Models/Connector.cs
download_net_runtime.py
publish_linux.sh
publish_osx.sh
publish_windows.sh

Closes #193 
Repeats everything done in https://github.com/space-wizards/SS14.Launcher/pull/119
Also updated `Robust.LoaderApi`: https://github.com/space-wizards/Robust.LoaderApi/pull/3
RT PR: https://github.com/space-wizards/RobustToolbox/pull/5552

Update to .NET 9

---

Directory.Packages.props
SS14.Launcher/Helpers.cs
SS14.Launcher/VcRedistCheck.cs
SS14.Launcher/Views/MainWindow.xaml.cs

Requires updating some other packages and renaming some import

Update Avalonia to 11.2.4

---

SS14.Launcher/App.xaml
SS14.Launcher/App.xaml.cs
SS14.Launcher/LauncherMessaging.cs
SS14.Launcher/Program.cs

Currently the quit shortcut under MacOS is not working, this changes the app to use Avalonia's built in desktop lifetime which handles the quit correctly.
Fixes https://github.com/space-wizards/SS14.Launcher/issues/170

Fix Command-Q not quitting the app under MacOS

---

SS14.Launcher/ViewModels/MainWindowTabs/ServerListTabViewModel.cs

Fixes https://github.com/space-wizards/SS14.Launcher/issues/212

Re-build the filters when selected language is changed

---

nix/package.nix

Add missing lib paths for nix config

---

SS14.Launcher/ViewModels/MainWindowTabs/ServerListTabViewModel.cs

I hate it when I get a lag on every letter entered

Throttle server search

---

SS14.Launcher/Localization/LocalizationManager.cs

it's 99% translated on weblate so why not

add hungarian to language options
