SS14.Launcher/Models/ConfigurationManager.cs, SS14.Launcher/Models/Connector.cs, SS14.Launcher/ViewModels/MainWindowTabs/OptionsTabViewModel.cs, SS14.Launcher/ViewModels/MainWindowViewModel.cs, SS14.Launcher/Views/MainWindowTabs/OptionsTabView.xaml
This adds a "compatibility mode" checkbox with an explaination of what it does (uses GLES2, presumably via ANGLE, to avoid any driver issues with GL 3) in preparation for when ANGLE enters the releases
=> "Compatibility Mode" to force GLES2 to deal with driver bugs

PublishFiles/SS14.Launcher
`readlink` without any other arguments fails with files that are not symbolic links and returns empty string
In other words it will only work if:
- the script is executed thru symbolic link
- the script is executed from within the applications directory (the readlink still fails but the working directory is valid for the rest of the script to run)
It does not work when calling the script directly, outside of the directory, eg: `./Downloads/SS14.Launcher`
=> Fix getting current directory in Linux shell script

SS14.Launcher/Models/Connector.cs, SS14.Launcher/Models/Updater.cs, SS14.Launcher/UriHelper.cs
*This has been tested both in it's intended use-case and with production servers (checking to ensure a content download works) to ensure it breaks nothing.*
It is clear from both the code handling `ConnectAddress` inference and basic common sense in regards to server hosting ease-of-use that a server should not need to be configured with it's own address unless necessary.
However right now content client zips need to have a URL provided.
I have a RobustToolbox PR in progress ( https://github.com/space-wizards/RobustToolbox/pull/2225 ) that integrates a way for the status server to host the content client zip.
But that needs support from the launcher for the process to be as simple as possible, because the launcher requires a URL to download the zip from, and that goes all the way back to …
=> Infer the presence of "client.zip" on the status host if necessary

SS14.Launcher/ViewModels/MainWindowLoginViewModel.cs, SS14.Launcher/Views/MainWindowLogin.xaml
This is a temporary solution to solve #46. It's not good and should be replaced with a real solution at some point.
Note: Changing between the logged-in Options menu and the logged-out menu makes the logging checkboxes unrepresentative of what's actually set.
=> Add checkbox in MainWindowLogin to toggle logging

SS14.Launcher/Utility/Libc.cs, SS14.Launcher/Utility/ZStd.cs
+ Adds a try/catch so that fallbacks will still be attempted if, say, `libdl` can't be found
+ Fixes used `libdl` library name
+ Tries `libzstd.so.1` (the actual wanted version) before `libzstd.so` (a potentially future or past version)
=> Fix zstd finding on Ubuntu 22.04 maybe

SS14.Launcher/LauncherVersion.cs
I have no idea if this has any repercussions but I noticed that the `UserAgent` was wrong when doing some funny business
=> Fix launcher version name

SS14.Launcher/Models/Data/DataManager.cs, SS14.Launcher/Models/Data/FavoriteServer.cs, SS14.Launcher/Models/Data/Migrations/Script0004_RaiseTime.sql, SS14.Launcher/ViewModels/MainWindowTabs/HomePageViewModel.cs, SS14.Launcher/ViewModels/MainWindowTabs/ServerEntryViewModel.cs, SS14.Launcher/Views/MainWindowTabs/ServerEntryView.xaml
Useful for organization.
About the "raise to top" workflow: I'm not sure of a better way to handle this sort of re-ordering given that the favorite servers are no longer strictly just an array.
Updating all of the favorite servers at once *could* do it but I don't think that'd be what would be wanted.
Maybe some sort of floating-point binary tree could work, but I think the fact I'm suggesting that gives an idea of the problem here.
(Note that the "Raise to top" button does not appear in the main servers list for hopefully obvious reasons.)
=> Button to raise favorite servers in the home tab

SS14.Launcher/Models/ServerStatus/ServerStatusCache.Data.cs, SS14.Launcher/Models/ServerStatus/ServerStatusCache.cs, SS14.Launcher/ViewModels/MainWindowTabs/ServerEntryViewModel.cs
Resolves #69 
Changes:
- New variables and piping for SoftMaxPlayers in a few classes
- Loads the "soft_max_players" field from each server's status page, into the new class vars
- Updates output from "[current] players" display to " [current] / [max] players" in Server List
Also requires Content.Server changes adding new field to status responses. PR link: https://github.com/space-wizards/space-station-14/pull/9365
Screenshot of updated launcher (using some rand values for max since Server changes are not live):
=> Read and display max players from server status

SS14.Launcher/Models/ServerStatus/IServerStatusData.cs, SS14.Launcher/Models/ServerStatus/ServerStatusCache.cs, SS14.Launcher/ViewModels/MainWindowTabs/ServerEntryViewModel.cs
ServerEntryViewModel used a callback to listen for changes to the server's PlayerCount property. When populating server info, the PlayerCount was set before the SoftMaxPlayerCount, so when generating the text representation of the server info, it didn't see the max player count. Initialize SoftMaxPlayerCount before PlayerCount to get the expected behaviour the first time the favorites window is rendered.
=> Avoid bug where favorites window wouldn't show max player count on first display

SS14.Launcher/Theme/Theme.xaml, SS14.Launcher/Theme/ThemeResources.xaml, SS14.Launcher/ViewModels/MainWindowTabs/ServerEntryViewModel.cs, SS14.Launcher/Views/MainWindowTabs/ServerEntryView.xaml, SS14.Launcher/Views/MainWindowTabs/ServerListTabView.xaml
During our time lurking, we've noticed that the launcher's UI is a common UI-related grumble. And when you look at it yourself, it's easy to see why! There's a lot of visual noise, blank space, and more. The launcher's server list is borderline unusable if you don't resize it above it's default resolution, as there's simply way too much visual clutter.
So this PR seeks to improve that through a basic UI quality pass.
Here's what the server list looks like before this PR:
And here's what the server list looks like after this PR:
Most of these changes are fairly self-explanatory, and were made largely through a mix of intuition and lurking chat.
The refresh button has been moved from the header to the footer, so that the server list's main controls are close to each other (with the side …
=> Server list makeover

SS14.Launcher/ViewModels/MainWindowTabs/HomePageViewModel.cs, SS14.Launcher/Views/MainWindowTabs/HomePageView.xaml
The suggestions window was fine earlier on in SS14 history to bring attention to other servers. Now, with the thriving SS14 ecosystem, it is a bit superfluous and also it's like weirdly small? idk I think it had its time in the sun.
=> Remove suggestions from launcher

SS14.Launcher/ViewModels/MainWindowTabs/NewsTabViewModel.cs
Before, pages like Downloads and the FAQ were also displayed in the News tab. With this change the launcher will have the same posts as displayed in https://spacestation14.io/post/.
=> Only display news posts in news tab

SS14.Launcher/Utility/ButtonExtensions.cs, SS14.Launcher/Views/MainWindowTabs/OptionsTabView.xaml, SS14.Launcher/Views/MainWindowTabs/OptionsTabView.xaml.cs
Closes #51 
https://github.com/space-wizards/SS14.Launcher/assets/39844191/f30ba0f5-0858-400f-9c09-5cab8f5d51a5
=> Give feedback to the user when they clear engines/clear server content

SS14.Launcher.Bootstrap/console.bat
`setx` sets the systems environmental values permanently which is probably a real big nono
accidently webedited to master branch i will delete this repo anyway after so is fine
=> Remove the x from setx

SS14.Launcher/ViewModels/MainWindowTabs/ServerEntryViewModel.cs
Fixes #86
After clicking Connect the connect button would still be focused and if you pressed Space/Enter you would trigger the connect again, causing an exception and crashing the client. Now we just unfocus right after the button is clicked so that that's no longer possible.
=> Unfocus connect button on press

SS14.Launcher/Models/ServerStatus/ServerListCache.cs
It can be kinda spammy right now and usually isn't very useful
=> Change log level for duplicate server message

SS14.Launcher/Views/MainWindowTabs/HomePageView.xaml.cs
To reproduce the bug this PR fixes:
1. Click "Run content/replay bundle"
2. When Windows file explorer opens for you to select the bundle, click Cancel instead
3. Launcher crashes due to the out-of-bounds exception since `result.Length == 0`
=> Fix canceling the replay file dialog causing a crash

Directory.Packages.props, SS14.Launcher/Program.cs, SS14.Launcher/SS14.Launcher.csproj, SS14.Loader/SS14.Loader.csproj
This is needed for the launcher to work on platforms without a bundled sqlite native library, including FreeBSD.
=> Add build property to use system SQLite

SS14.Launcher/Views/HubSettingsDialog.xaml
Newlines stopped taking effect, probably after Avalonia 11 update. This returns them.
=> Fix hub settings tooltip

SS14.Launcher/ConfigConstants.cs
These really shouldn't be strings and should use the standard uri type instead. It tries to parse the string as uri every time the button is pressed, which currently crashes due to the typo.
=> Fix typo in translations docs url

SS14.Launcher.FakeRobustToolbox/Robust.Client/Robust.Client.csproj
After #162, this updates the only remaining project requiring dotnet 6.0. 
This also removes 6.0 from the nix package.
=> Remove dotnet SDK 6.0 dependency.

SS14.Launcher/LauncherDiagnostics.cs
I can't believe it's just a burning memory
=> Add system memory to launcher diagnostics

SS14.Launcher/Views/ServerInfoLinkControl.xaml
For the buttons in the server info, adds a tooltip showing the URL you'll be brought to on clicking.
=> Add tooltips with URL to server info buttons

SS14.Launcher/Models/Connector.cs, SS14.Loader/Program.cs, SS14.Loader/SS14.Loader.csproj
Fixes SS14.Loader on FreeBSD:
- `USE_SYSTEM_SQLITE` was added for SS14.Loader a while ago, but wasn't actually set in the build properties. Define this correctly so that FreeBSD sets `USE_SYSTEM_SQLITE`
- Launch `SS14.Loader` like we're on Linux
=> SS14.Loader fixes for FreeBSD

SS14.Launcher/Assets/Locale/en-US/text.ftl, SS14.Launcher/Helpers.cs, SS14.Launcher/Models/Connector.cs, SS14.Launcher/Models/Data/DataManager.cs, SS14.Launcher/Models/Data/Migrations/Script0007_PrivacyPolicy.sql, SS14.Launcher/Models/ServerInfo.cs, SS14.Launcher/ViewModels/ConnectingViewModel.cs, SS14.Launcher/Views/ConnectingOverlay.xaml, SS14.Launcher/Views/ServerInfoLinkControl.xaml.cs
Servers can now provide privacy policy information via their info API. If provided, users will be prompted to accept the policy while being presented with a link to open it.
Accepted privacy policies are stored in the launcher's settings database. Servers can report changes in their privacy policy version, in which case the user will be re-prompted with a different message.
Fixes https://github.com/space-wizards/SS14.Launcher/issues/194
=> Implement privacy policy support

SS14.Launcher/Theme/Theme.xaml, SS14.Launcher/Views/MainWindowTabs/HomePageView.xaml, SS14.Launcher/Views/MainWindowTabs/ServerEntryView.xaml, SS14.Launcher/Views/MainWindowTabs/ServerListTabView.xaml
This should fix column layouts for other languages, and make it easier to add new columns.
Before/after for French (see column headers):
Before/after for English:
=> Replace some magic column sizing numbers with SharedSizeGroup

SS14.Launcher/Controls/TimerTextCell.xaml.cs
This would cause DispatcherTimer.RunOnce to throw an exception as it expects a positive TimeSpan.
=> Fix a crash which would occur if the round start time was in the future.

SS14.Launcher/Views/MainWindowTabs/ServerEntryView.xaml
During the post-round lobby state the round timer is still present, so the round status must be checked.
=> Fix post-round lobby status indicator

SS14.Launcher/Theme/ThemeServerList.axaml
Restores the original behaviour of the scrollbar being hidden if the content does not need to scroll (despite no scrollbar properties being changed).
=> Fix inexplicably different scrollbar behaviour

SS14.Launcher/Views/MainWindowTabs/HomePageView.xaml, SS14.Launcher/Views/MainWindowTabs/ServerListTabView.xaml
Currently the two server list tabs share only one button (Refresh) and it’s in a different place on each tab which makes it frustrating to find each time.
This changes the layout of the home tab buttons, putting the Refresh button in the bottom right to keep it its location consistent across both tabs.
=> Make refresh button position consistent

SS14.Launcher/Models/Connector.cs
See https://github.com/space-wizards/RobustToolbox/pull/5563
=> Supply engine version CVar from launcher

SS14.Launcher/Controls/TimerTextCell.xaml.cs
We see u there, StarHorizon, with ur 26 hour long round times, of which the launcher only displays as 2h
(This PR swaps the use of `Hours` in the round timer display with a `Math.Floor(TotalHours)`, allowing round times longer than 24h to be properly displayed)
Before this change:
After this change:
=> Allows round timers to gracefully surpass 24h

SS14.Launcher/Assets/Locale/en-US/text.ftl
=> Fix a small typo in the intel degrade CPU warning at first start
